"""link user to jobs

Revision ID: d1f7d5a58cf8
Revises: 67af2e0d4366
Create Date: 2025-12-16 21:42:00.989113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f7d5a58cf8'
down_revision: Union[str, Sequence[str], None] = '67af2e0d4366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
